name: WebGOAT Setup
on: push
jobs:
  webgoat-job:
    runs-on: self-hosted
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3


      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2


      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}


      - name: Pull and run Docker container
        run: docker run -d --name webgoat -p 127.0.0.1:8080:8080 -p 127.0.0.1:9090:9090 -e TZ=Europe/Istanbul webgoat/webgoat

########## CodeQL 

  codeql-job:
    runs-on: self-hosted
    needs: webgoat-job

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Download Docker container state
      uses: actions/download-artifact@v3
      with:
        name: webgoat-container
        path: /var/lib/docker/containers

    - name: Initialize the CodeQL engine
      uses: github/codeql-action/init@v2
      with:
        languages: 'java'

    - name: Autobuild
      uses: github/codeql-action/autobuild@v2

    - name: Perform CodeQL Analysis
      uses: github/codeql-action/analyze@v2
      with:
        category: 'security' 

