name: WebGOAT Setup
on: push
jobs:
  webgoat-job:
    runs-on: self-hosted
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3


      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2


      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}


      - name: Pull and run Docker container
        run: docker run -d --name webgoat -p 127.0.0.1:8080:8080 -p 127.0.0.1:9090:9090 -e TZ=Europe/Istanbul webgoat/webgoat


      - name: Save Docker container state
        uses: actions/upload-artifact@v3
        with:
          name: webgoat-container
          path: /var/lib/docker/containers
